#ifndef __AL_ERROR_H__
#define __AL_ERROR_H__

#define AL_OK								0
#define AL_ERROR_INVALID_POINTER			-1000
#define AL_ERROR_INVALID_ARGUMENT			-1001

#define AL_ERROR_SO_UTIL_INVALID_ELFMAG		-2000
#define AL_ERROR_SO_UTIL_EXEC_SEG_MISSING	-2001
#define AL_ERROR_SO_UTIL_INCOMPLETE			-2002
#define AL_ERROR_SO_UTIL_UNKNOWN_RELOC_TYPE	-2003
#define AL_ERROR_SO_UTIL_SYMBOL_NOT_FOUND	-2004

#define AL_ERROR_SYMT_SYMBOL_NOT_FOUND		-3000
#define AL_ERROR_SYMT_TABLE_SIZE			-3001

#define AL_ERROR_MAIN_KUBRIDGE_NOT_FOUND	-4000

#endif